
const constants = {
    departments: [
        { 'any': 'Any' },
        { 'ACCT': 'Accounting' },
        { 'AGBU': 'Agribusiness' },
        { 'AGR': 'Agriculture' },
        { 'AHSS': 'Arts/Humanities/Social Sci' },
        { 'ANSC': 'Animal Science' },
        { 'ANTH': 'Anthropology' },
        { 'AQUA': 'Aquaculture' },
        { 'ARAB': 'Arabic' },
        { 'ARTH': 'Art History' },
        { 'ASCI': 'Arts & Sciences' },
        { 'AVC': 'Art & Visual Culture' },
        { 'BADM': 'Business Administration' },
        { 'BINF': 'Bioinformatics' },
        { 'BIOC': 'Biochemistry' },
        { 'BIOL': 'Biology' },
        { 'BIOM': 'Biomedical Science' },
        { 'BIOP': 'Biophysics' },
        { 'BIOT': 'Biotechnology' },
        { 'BOT': 'Botany' },
        { 'BUS': 'Business' },
        { 'CCJP': 'Criminology/Criminal Justice' },
        { 'CDE': 'Capacity Development/Extension' },
        { 'CHEM': 'Chemistry' },
        { 'CHIN': 'Chinese' },
        { 'CIS': 'Computing & Information Sci.' },
        { 'CLAS': 'Classical Studies' },
        { 'CLIN': 'Clinical Studies' },
        { 'CME': 'Commerce,Management&Economics' },
        { 'COOP': 'Co-Op Education' },
        { 'CROP': 'Crop Science' },
        { 'CRWR': 'Creative Writing' },
        { 'DAFL': 'Agri-Food Leadership (diploma)' },
        { 'DAGR': 'Ag. & Equine Studies (dip)' },
        { 'DENM': 'Environmental Mngt (diploma)' },
        { 'DEQN': 'Equine (Diploma)' },
        { 'DFN': 'Food & Nutrition (diploma)' },
        { 'DHRT': 'Horticulture (diploma)' },
        { 'DTM': 'Turf Management (diploma)' },
        { 'DVT': 'Veterinary Technology (dip)' },
        { 'ECON': 'Economics' },
        { 'ECS': 'Early Childhood Studies' },
        { 'EDRD': 'Env. Design/Rural Development' },
        { 'ENGG': 'Engineering' },
        { 'ENGL': 'English' },
        { 'ENVB': 'Environmental Biology' },
        { 'ENVM': 'Environmental Management' },
        { 'ENVS': 'Environmental Sciences' },
        { 'EQN': 'Equine' },
        { 'EURO': 'European Studies' },
        { 'FARE': 'Food, Agr & Resource Economics' },
        { 'FCSS': 'Family/Community Social Servic' },
        { 'FDNT': 'Food & Nutritional Science' },
        { 'FINA': 'Fine Art' },
        { 'FOOD': 'Food Science' },
        { 'FRAN': 'Family Rel\'s/Applied Nutrition' },
        { 'FREN': 'French Studies' },
        { 'FRHD': 'Family Relations & Human Dev.' },
        { 'FSQA': 'Food Safety & Quality Assuranc' },
        { 'GEOG': 'Geography' },
        { 'GERM': 'German Studies' },
        { 'GERO': 'Gerontology' },
        { 'GREK': 'Greek Studies' },
        { 'HHNS': 'Human Health/Nutritional Sci' },
        { 'HISP': 'Hispanic Studies' },
        { 'HIST': 'History' },
        { 'HK': 'Human Kinetics' },
        { 'HORT': 'Horticultural Science' },
        { 'HROB': 'Human Resource/Organizat Behav' },
        { 'HTM': 'Hospitality & Tourism Mngt' },
        { 'HUMN': 'Humanities' },
        { 'IBIO': 'Integrative Biology' },
        { 'IDEV': 'International Development Std.' },
        { 'IMPR': 'Improvisation' },
        { 'INDG': 'Indigenous Studies' },
        { 'INT': 'Interdisciplinary' },
        { 'IPS': 'Interdisciplinary Physical Sci' },
        { 'ISS': 'Interdisciplinary Social Sci.' },
        { 'ITAL': 'Italian Studies' },
        { 'JUST': 'Justice Studies' },
        { 'KIN': 'Kinesiology' },
        { 'LACS': 'Latin American/Caribbean St' },
        { 'LARC': 'Landscape Architecture' },
        { 'LAT': 'Latin' },
        { 'LEAD': 'Leadership' },
        { 'LING': 'Linguistics' },
        { 'LRS': 'Land Resource Science' },
        { 'LTS': 'Literary/Theatre Studies' },
        { 'MATH': 'Mathematics' },
        { 'MBG': 'Molecular Biology & Genetics' },
        { 'MCB': 'Molecular & Cellular Biology' },
        { 'MCM': 'McMaster' },
        { 'MCS': 'Marketing & Consumer Studies' },
        { 'MDST': 'Media Studies' },
        { 'MGMT': 'Management' },
        { 'MICR': 'Microbiology' },
        { 'MUSC': 'Music' },
        { 'NANO': 'Nanoscience' },
        { 'NEUR': 'Neuroscience' },
        { 'NRS': 'Natural Resource Studies' },
        { 'NUTR': 'Nutrition' },
        { 'OAGR': 'Organic Agriculture' },
        { 'PABI': 'Pathobiology' },
        { 'PATH': 'Pathology' },
        { 'PBIO': 'Plant Biology' },
        { 'PHIL': 'Philosophy' },
        { 'PHYS': 'Physics' },
        { 'PLNT': 'Plant Agriculture' },
        { 'POLS': 'Political Science' },
        { 'POPM': 'Population Medicine' },
        { 'PORT': 'Portuguese' },
        { 'PSYC': 'Psychology' },
        { 'REAL': 'Real Estate & Housing' },
        { 'RPD': 'Rural Planning & Development' },
        { 'RST': 'Rural Studies' },
        { 'SART': 'Studio Art' },
        { 'SCMA': 'Science & Math' },
        { 'SOAN': 'Sociology & Anthropology' },
        { 'SOC': 'Sociology' },
        { 'SPAN': 'Spanish' },
        { 'STAT': 'Statistics' },
        { 'THST': 'Theatre Studies' },
        { 'TOX': 'Toxicology' },
        { 'TRMH': 'Tourism and Hospitality' },
        { 'UNIV': 'Interdisciplinary University' },
        { 'VETM': 'Veterinary Medicine' },
        { 'WAT': 'Waterloo' },
        { 'WLU': 'Wilfrid Laurier' },
        { 'WMST': 'Women\'s Studies' },
        { 'XSEN': 'Seneca College' },
        { 'XSHR': 'Sheridan College' },
        { 'ZOO': 'Zoology' }
    ],
    levels: [
        { 'any': 'Any' },
        { '010': 'Diploma - 1st Semester' },
        { '020': 'Diploma - 2nd Semester' },
        { '030': 'Diploma - 3rd Semester' },
        { '040': 'Diploma - 4th Semester' },
        { '100': 'First Year' },
        { '200': 'Second Year' },
        { '300': 'Third Year' },
        { '400': 'Fourth Year' },
        { '500': 'Graduate' },
        { '600': 'Graduate' },
        { '700': 'Graduate' },
        { '800': 'Graduate' },
        { '900': 'Transfer Credit' }
    ]
}

export default constants

let reduceFn = (result, item, index) => {
    let value = Object.keys(item)[0]
    result[value] = item[value]
    return result
}

export const labels = {
    departments: constants.departments.reduce(reduceFn, {}),
    levels: constants.levels.reduce(reduceFn, {})
}